### ISSUE TITLE
Publish to Google Play.

### ISSUE THREAD

**Issue by rokejulianlockhart** [MuntashirAkon/SetEdit#20]

**Comment by MuntashirAkon** [comment]
> I don't know what you're referring to.

Google Play Store delivers more malware (spyware, trojan, adware) than any other stores combined.

> Also, you published [#20 (comment)](https://github.com/MuntashirAkon/SetEdit/issues/20#issuecomment-1496012764) twice.

GitHub published it twice, probably due to network issues.

> Anyway, if you don't, you realize that someone else will, right? You've published FOSS software. You might as well publish an official version there for those who don't know about F-Droid in order to prevent copycats just taking your work.

People are welcome to copy, publish or whatever they want to do with my works as long as they comply with the GPL license. BTW, they cannot publish this particular app in Google Play Store. Google Play Store requires all the new apps to target at least API 32, and this app only targets API 22 because setting it to any higher SDK will make the app useless.

**Comment by rokejulianlockhart** [comment]
If the mandatory SDK level is incompatible, then indeed this discussion is useless. Thanks for the responses.

**Comment by roke-julian-lockhart** [comment]
@MuntashirAkon:

1.  ~~If the mandatory SDK level is incompatible, then indeed this discussion is useless. Thanks for the responses.~~
1.  Regarding API levels, https://play.google.com/store/apps/details?id=com.netvor.settings.database.editor#:~:text=help_outline-,Settings%20Database%20Editor,-NetVor%20%2D%20Android appears to demonstrate otherwise.

Also, I don't understand how the rest is relevant to this application.

**Comment by MuntashirAkon** [comment]
> https://play.google.com/store/apps/details?id=com.netvor.settings.database.editor, so you're definitely wrong about API levels.

Really? Did you even install the app? It literally asks you to download another app in order for it to work properly.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/MuntashirAkon/SetEdit/issues/20#issuecomment-1496912770

@MuntashirAkon, indeed. My apologies.

**Comment by MuntashirAkon** [comment]
Not sure why a notification was triggered from this post.
