### ISSUE TITLE
Doesn't support newer Android version 

### ISSUE THREAD

**Issue by rajarshikhatua100** [MuntashirAkon/SetEdit#31]
the app doesn't support newer android version like Android 14 and 15

**Comment by drogga** [comment]
By doesn't support you mean what exactly: You can't install it or it doesn't accept made changes to the tables when you "activate" it using the write secure settings command ?

_Barely anything works on A.14, even worse one (15) barely just came out as a first dev. preview and we are already talking about it..._

**Comment by rajarshikhatua100** [comment]
it doesn't ask for permission or anything it just changes values but it doesn't apply the values

**Comment by drogga** [comment]
Unfortunately, I know what you mean, I've had the same problem with **Settings Database Editor** [by NetVor]: https://play.google.com/store/apps/details?id=com.netvor.settings.database.editor and IDK why or did they fixed it, but I haven't had the same with this one or **SetEdit** [by 4A], but that was on A.8 and Samsung, don't know anything about 14+, nor have it setup on anything to test myself, in any case, please tag/mention the owner (Muntashir), he rarely responds, but let's hope he does this time...

**Comment by MuntashirAkon** [comment]
SetEdit modifies the settings database using the framework-provided content provider using a permission that is already granted by the system (which is why it has to target SDK 22). It only needs a permission that needs to be granted manually for modifying the secure and global table. Hence, this should still work on Android 14. However, even in the previous versions of Android, not all settings worked because they were either removed or no longer used. So, make sure you're altering a setting that is still used in A14.

**Comment by rajarshikhatua100** [comment]
> make sure you're altering a setting that is still used in A14.

It's working after granting the permission, but sometimes it doesn't ask for the permission right away, and also it doesn't install due to target sdk maybe, I used [this](https://github.com/zacharee/InstallWithOptions) to get around it. but the "4A Settings Database Editor" works just fine, I checked the api level of that app using Boundo and it seems its using the letest api level, I attached the screenshots below 
![Screenshot_20240308_165521_Package installer](https://github.com/MuntashirAkon/SetEdit/assets/77912617/d11a1d51-cc14-43e8-982e-d1247d09354f)
![Screenshot_20240308_165547_Install with Options](https://github.com/MuntashirAkon/SetEdit/assets/77912617/000c27c8-f281-42e0-90e1-062a095c5053)
![Screenshot_20240308_164903_Boundo](https://github.com/MuntashirAkon/SetEdit/assets/77912617/2e61e574-26ba-4d3c-89cb-f78530954f43)
![Screenshot_20240308_164909_Boundo](https://github.com/MuntashirAkon/SetEdit/assets/77912617/ca284022-afe4-4ad1-941f-f6b261d6c55a)

**Comment by MuntashirAkon** [comment]
Some setting items won't work if SetEdit targets API 34. There's no way to bypass this other than using a provider APK that targets API 22 or earlier that some other apps use. I don't have any plans to do such a thing since this app isn't available on Google Play anyway. So, there's no reason to complicate things.
