### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MuntashirAkon/SetEdit#5]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by drogga** [comment]
@MuntashirAkon
I'm not sure why the issue ticket's Author decided to close this, but that's a great idea IMO, also add them to the ReadMe here and mention the need of `--bypass-low-target-sdk-block` for A.14 while you are editing it ;)

**Comment by mondlicht-und-sterne** [comment]
> @MuntashirAkon I'm not sure why the issue ticket's Author decided to close this, but that's a great idea IMO, also add them to the ReadMe here and mention the need of `--bypass-low-target-sdk-block` for A.14 while you are editing it ;)

My issue is from 2021, now it's 2024, so I had closed the issue.

**Comment by MuntashirAkon** [comment]
FYI, you closed it after waiting only a month. I've seen issues getting fixed after more than 20 years in the Firefox issue tracker.

**Comment by MuntashirAkon** [comment]
Added in 7e3facf43a8880feaab02af6b06bb70fe79fc544

**Comment by drogga** [comment]
Nice, consider linking them in the ReadMe as well ± the icon, just like in the A.M. repo, even tho there they look more professional with dark/lite theme there.

**Comment by MuntashirAkon** [comment]
@drogga: AM is intended for a more wider audience than SetEdit which is why it has a slightly better README. If AM is a side-project, SetEdit (and other apps) can be considered even less than that. Because they are mostly developed for the benefit of the existing audience or those who are looking for FOSS alternatives. No more than that, and I'll be glad to hand them over to somebody else if they are capable of maintaining them. The only apps I actively use are AM, BCL, QKSMS/Messages and Aard 2 (the latter two have no public release).
