### ISSUE TITLE
Removed setting when value is 0

### ISSUE THREAD

**Issue by bluems** [MuntashirAkon/SetEdit#7]
In System Table, when I chaned firstly "csc_pref_camera_forced_shuttersound_key" value 0, this setting is removed and no show in "System Table".
At this time, I add manually setting "Add new setting" and reload table. 
If you do this, the settings will remain permanent.

**Comment by drogga** [comment]
@bluems is this only happens in\on the "System Table" and does it also happen with the original "SetEdit" (Settings Database Editor) app from Play Store ?, because it might be a issue\bug with your OS system (ROM\Firmware), rather than the app, because so far I only changed the value of "heads_up_notifications_enabled" [1>0] under\in the "Global Table" - it's still there, wasn't removed, even after reboots...

**Comment by bluems** [comment]
@drogga Yes. My case is only happens  "System Table" and Android 11. I tested Android 11 and Samsung Galaxy S20 Ultra and S21 Ultra. 
After  I add manually, It didn't cause any problems even after rebooting.

**Comment by drogga** [comment]
It appears that it's not the app's fault then...
You can close this then.
