### ISSUE TITLE
Support for exporting table and property data values

### ISSUE THREAD

**Issue by TacoTheDank** [MuntashirAkon/SetEdit#8]
Maybe as a JSON or something. Ideally, each table would be able to be exported individually.

This would be a cool feature to have. Maybe importing would be nice as well, but that's not really important to me.

**Comment by drogga** [comment]
Maybe modified and added strings _(items)_ can be highlighted, similarly to how Firefox and Chrome does for their "config" | "flags" values...

@MuntashirAkon - When I tried to add "enable_freeform_support" in the Global Table, I got "Unexpected failure: Your system software has rejected this edit." message, but "the original" _(other)_ SetEdit was able to add it without a problem, the string is supported by my system and it's active _(it works)_ now, so I have no idea on why this strange behavior happened.

**Comment by drogga** [comment]
Maybe modified and added strings _(items)_ can be highlighted, similarly to how Firefox and Chrome does for their "config" | "flags" values when they are changed or a new custom ones being added...

@MuntashirAkon - When I tried to add "enable_freeform_support" in the Global Table, I got "Unexpected failure: Your system software has rejected this edit." message, but "the original" _(other)_ SetEdit was able to add it without a problem, the string is supported by my system and it's active _(it works)_ now, so I have no idea on why this strange behavior happened.

**Comment by MuntashirAkon** [comment]
> Maybe modified and added strings _(items)_ can be highlighted, similarly to how Firefox and Chrome does for their "config" | "flags" values when they are changed or a new custom ones being added...

Open another issue for this as it's not related to the issue.

> When I tried to add "enable_freeform_support" in the Global Table, I got "Unexpected failure: Your system software has rejected this edit." message, but "the original" _(other)_ SetEdit was able to add it without a problem, the string is supported by my system and it's active _(it works)_ now, so I have no idea on why this strange behavior happened.

I've no idea either since you haven't shared any logs (also unrelated to this feature).

**Comment by drogga** [comment]
So it turns out that I thought I previously (back when I installed it) granted the ADB Shell permission to write the Secure Settings, but I actually haven't - got confused by the "App info" > "Modify system settings" > "Yes", _because some apps can write and change values in some tables, without granting any permissions, especially "special" ones, just like those 'Dark Mode' apps, which can change the system's theme (or only on apps that support it, like your's) on system's where the toggle is missing, even on below A.7_ and your app doesn't tell \ prompt you to allow the permission on the other 2 tables "Secure" & "Global" because without the Perm., only the "System Table" can be manipulated, it doesn't even tells you that "Android Properties", "Java Properties" & "Linux Environment" cannot be edited with the app at all, but only be read when you try to Add or Edit something in those 3 !, also the default text in new item name setting and the value in the input fields is annoying, plus the dialog windows aren't native, so they can't be brought down on the bottom of the screen by Samsung's One UI, because since v1.1 you started using theme(s) and samsung even prompt's me to make it fullscreen \ change the aspect ratio, when the screen's one is unconventional 18.5:9 (taller screens is a modern trend).

**Comment by MuntashirAkon** [comment]
Implemented in 34d5870.

**Comment by TacoTheDank** [comment]
Thanks!

**Comment by drogga** [comment]
Now search doesn't work at all _(other things are not how they are supposed to be too)_, it's like (@)MuntashirAkon didn't tested it at all or barely, especially this particular update...

**Comment by TacoTheDank** [comment]
> Now search doesn't work at all _(other things are not how they are supposed to be too)_, it's like (@)MuntashirAkon didn't tested it at all or barely, especially this particular update...
> 
> I give up !

I wasn't even aware there was a search function. Regardless, the best way to have your problems addressed is to be nicer to the people who maintain this FOSS software. I understand where the frustration can come from (having to deal with rather blatant bugs in other software), but it doesn't hurt to at least be a little nicer...

**Comment by MuntashirAkon** [comment]
> Now search doesn't work at all _(other things are not how they are supposed to be too)_, it's like (@)MuntashirAkon didn't tested it at all or barely, especially this particular update...
> 
> I give up !

At this point, you didn't even listen to me and created new issues with the existing problems. So, why should I be care about your words when you can't do simple things like that? And you already knew very well why searching is problematic in the first three lists (and it's not too difficult to suspect that the problem might've arisen from that).

We invest our time and resources in developing libre software, which we could've invested in some places and earned actual money or spent with our friends and family or simply watched some good TV shows or movies, in hopes that the software we develop would be useful to others and that they would also contribute back in some other ways such opening issues. If you don't feel the obligation to do that and start complaining as if you're my project manager, there's no reason to consider you as the user of this app.
